// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitutde")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = "ace0b7e9-1c82-4395-81cb-8398b1419d08",
                            Category = "Music",
                            City = "New York",
                            Date = new DateTime(2025, 2, 25, 13, 50, 46, 206, DateTimeKind.Utc).AddTicks(7793),
                            Description = "Live music concert featuring popular bands.",
                            IsCancelled = false,
                            Latitude = 40.750500000000002,
                            Longitutde = -73.993399999999994,
                            Title = "Music Concert",
                            Venue = "Madison Square Garden"
                        },
                        new
                        {
                            Id = "67994be0-151d-4ea9-9e89-cfa34524bf84",
                            Category = "Technology",
                            City = "San Francisco",
                            Date = new DateTime(2025, 3, 20, 13, 50, 46, 206, DateTimeKind.Utc).AddTicks(7809),
                            Description = "Annual technology conference with keynote speakers.",
                            IsCancelled = false,
                            Latitude = 37.784700000000001,
                            Longitutde = -122.4011,
                            Title = "Tech Conference",
                            Venue = "Moscone Center"
                        },
                        new
                        {
                            Id = "3e8a617f-57c2-4e5b-825c-1302d2c1237b",
                            Category = "Sports",
                            City = "Boston",
                            Date = new DateTime(2025, 3, 22, 13, 50, 46, 206, DateTimeKind.Utc).AddTicks(7825),
                            Description = "City-wide marathon for charity.",
                            IsCancelled = false,
                            Latitude = 42.355400000000003,
                            Longitutde = -71.065600000000003,
                            Title = "Marathon",
                            Venue = "Boston Commons"
                        },
                        new
                        {
                            Id = "9e62464f-b12a-4afa-96bb-afe7f12cc178",
                            Category = "Art",
                            City = "Paris",
                            Date = new DateTime(2025, 3, 2, 13, 50, 46, 206, DateTimeKind.Utc).AddTicks(7832),
                            Description = "Showcasing modern and contemporary art.",
                            IsCancelled = false,
                            Latitude = 48.860599999999998,
                            Longitutde = 2.3376000000000001,
                            Title = "Art Exhibition",
                            Venue = "Louvre Museum"
                        },
                        new
                        {
                            Id = "09917fd9-8a99-4613-a1a3-2b58caec9f12",
                            Category = "Food",
                            City = "Los Angeles",
                            Date = new DateTime(2025, 3, 7, 13, 50, 46, 206, DateTimeKind.Utc).AddTicks(7840),
                            Description = "A celebration of world cuisines and local food vendors.",
                            IsCancelled = false,
                            Latitude = 34.040700000000001,
                            Longitutde = -118.26900000000001,
                            Title = "Food Festival",
                            Venue = "LA Convention Center"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
